apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  api_url: "http://educated-guess-backend:8000/api/v1"
  mongodb_db_name: "educated_guess"
  allowed_origins: "http://localhost:3000,https://educatedguess.example.com"
  app_name: "Educated Guess API"
  app_version: "1.0.0"
